# syntax=docker/dockerfile:1

# Base: ruby:3.3-slim (Debian/glibc), not ruby:3.3-alpine.
# See docs/decision-log.html (D5): Alpine's musl libc breaks some native-extension
# gems outright and has been observed adding ~15-20% RSS memory at steady state
# under Rails -- not worth it before the app's own gem set has been validated
# against musl. Revisit once that validation happens.
ARG RUBY_VERSION=3.3

FROM ruby:${RUBY_VERSION}-slim AS base

WORKDIR /rails

# Runtime-only OS packages, shared by the build and final stages:
#   libpq5     - Postgres client library the `pg` gem links against at runtime
#                (libpq-dev, needed only to *compile* the gem, lives in the
#                build stage below and never reaches this image).
#   libjemalloc2 - glibc's malloc fragments badly under Puma's threaded workers
#                over long process lifetimes; jemalloc is the standard fix and
#                costs ~300KB. Only relevant because we're on glibc (slim) --
#                musl (Alpine) uses a different allocator, another reason D5
#                deferred that move rather than combining two variables at once.
RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y libpq5 libjemalloc2 \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development:test" \
    LD_PRELOAD="libjemalloc.so.2"

# ---- build stage: compiles gems and precompiles assets, discarded after ----
FROM base AS build

# Build tooling lives only here -- none of it reaches the final image.
RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

COPY Gemfile Gemfile.lock ./
RUN bundle install \
    && rm -rf "${BUNDLE_PATH}"/ruby/*/cache \
               "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git

COPY . .

# Speeds up boot in the runtime image; safe to skip if the app doesn't use bootsnap.
RUN bundle exec bootsnap precompile app/ lib/

# SECRET_KEY_BASE_DUMMY lets `assets:precompile` run without the real
# RAILS_MASTER_KEY / credentials being available at build time.
RUN SECRET_KEY_BASE_DUMMY=1 bin/rails assets:precompile

# ---- final stage: only what's needed to run the app ----
FROM base

# Non-root, fixed-UID user (matches Rails 8's own generated Dockerfile
# convention) so this container is never running as root and lines up
# cleanly with an ECS task definition's non-root user expectations.
RUN groupadd --system --gid 1000 rails \
    && useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/false

COPY --from=build --chown=rails:rails "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build --chown=rails:rails /rails /rails

RUN chown -R rails:rails /rails/db /rails/log /rails/storage /rails/tmp

USER 1000:1000

# Rails' default `bin/docker-entrypoint` (generated by `rails new` since
# Rails 7) runs `rails db:prepare` before exec-ing the CMD below -- this is
# the "migrations run at startup via entrypoint" assumption also documented
# in .github/workflows/rails-deploy.yml. Two things that assumption depends
# on -- see README.md's assumptions list for the full explanation:
#   1. Migrations must be expand/contract (additive, backward-compatible with
#      the previous release) because minimumHealthyPercent: 100 keeps old and
#      new task revisions serving traffic against this database at once.
#   2. Multiple new tasks call db:prepare concurrently on every rolling
#      deploy; Rails' migrator takes a Postgres advisory lock so this is
#      normally safe, but isn't guaranteed on the very first boot of a brand
#      new database before that locking is established.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Only the port the app actually serves on. No SSH, no extra services.
EXPOSE 3000
ENV PORT="3000"

# No curl in this image -- one fewer general-purpose network tool sitting in
# a container that doesn't otherwise need one. Ruby is already present, so a
# one-line request against Rails' built-in `/up` health route (added in 7.1)
# does the same job for ~0 added size.
#
# IMPORTANT: this instruction is inert on ECS Fargate. ECS only monitors
# health checks declared in the task definition's own `healthCheck` field --
# it ignores a Docker image's embedded HEALTHCHECK entirely unless that same
# check is duplicated there. It's kept here because it's real for `docker
# run`/docker-compose and documents the intended check, but the ALB target
# group (hitting this same `/up` path) is what actually governs ECS traffic
# routing in production -- see OBSERVABILITY.md's Rails section for that
# story and for the task-definition healthCheck block to mirror this with.
HEALTHCHECK --interval=15s --timeout=3s --start-period=30s --retries=2 \
    CMD ruby -e '\
        require "net/http"; \
        exit(Net::HTTP.get_response(URI("http://localhost:#{ENV["PORT"]}/up")).code == "200" ? 0 : 1)' \
    || exit 1

# Production by default; override RAILS_ENV/PORT at `docker run` / in the ECS
# task definition to change either without rebuilding the image.
CMD ["./bin/rails", "server"]
